<style>
  .wficons-filter-tabs {
    display: flex;
    gap: 8px;
    margin-bottom: 20px;
    justify-content: center;
    flex-wrap: wrap;
  }

  .wficons-filter-tabs button {
    padding: 8px 20px;
    background: var(--neut2);
    border: 2px solid transparent;
    cursor: pointer;
    transition: var(--trans3);
    font-family: var(--font1b);
    font-size: 14px;
    border-radius: 5px;
  }

  .wficons-filter-tabs button:hover {
    background: var(--neut3);
  }

  .wficons-filter-tabs button.active {
    background: var(--prin);
    color: var(--bran);
    border-color: var(--prin--);
  }

  .wficons {
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
    align-items: center;
    justify-content: center;
  }

  .wficons li {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  .wficons li a {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 150px;
    height: 9rem;
    background: var(--neut2);
    justify-content: center;
    cursor: pointer;
    transition: var(--trans3);
    border-radius: 5px;
  }

  .wficons li a:hover {
    background: var(--neut3);
    transform: translateY(-2px);
  }

  .wficons li a div i {
    font-size: 4rem;
    color: var(--prin--);
  }

  .wficons li a p {
    font-size: 12px;
    font-family: var(--font1b);
    text-wrap: initial;
    text-align: center;
    margin-top: 8px;
  }

  .wficons li a.copied {
    background: var(--suce);
    color: var(--bran);
  }

  .wficons li a.copied i {
    color: var(--bran);
  }
</style>
<section>
  <div class="g-xg">
    <div class="topo">
      <h1>WfIcones</h1>
      <nav class="listmenu-d">
        <ol class="listmenu">
          <li class="listmenu-item"><a href="#">Home</a></li>
          <li class="listmenu-item active">WfIcones</li>
        </ol>
      </nav>
    </div>
    <div class="l">
      <div class="co12-g et3">
        <p>
          Biblioteca completa de ícones cuidadosamente criados para designers
          e desenvolvedores. Use <b>wf</b> para ícones regulares, <b>wfs</b> para sólidos e <b>wfl</b> para logos.
        </p>
      </div>
    </div>
    <div class="l">
      <div class="co12-g" style="margin-bottom: 20px;">
        <!-- Abas de Filtro -->
        <div class="wficons-filter-tabs">
          <button class="filter-btn active" data-filter="all">Todos</button>
          <button class="filter-btn" data-filter="wf">Regular (wf)</button>
          <button class="filter-btn" data-filter="wfs">Solid (wfs)</button>
          <button class="filter-btn" data-filter="wfl">Logos (wfl)</button>
        </div>

        <!-- Busca -->
        <div style="display: flex; gap: 8px; align-items: center; justify-content: center; margin-top: 20px;">
          <input
            id="icon-search"
            type="text"
            class="input"
            placeholder="Buscar ícones (ex.: home, user, rocket)"
            style="max-width: 520px" />
          <span class="Tgray" id="icon-count"></span>
        </div>
      </div>

      <!-- Lista de Ícones -->
      <ul class="wficons" id="wficons-list" data-wf-icons-init="skip"></ul>
    </div>
  </div>
</section>
<script>
  (function () {
    // Ícones REGULARES (wf) - 967 ícones
var REGULAR_ICONS = [
  "500px",
  "99designs",
  "abacus",
  "accessibility",
  "add-to-queue",
  "adjust",
  "adobe",
  "airbnb",
  "alarm",
  "alarm-add",
  "alarm-exclamation",
  "alarm-off",
  "alarm-snooze",
  "album",
  "algolia",
  "align-justify",
  "align-left",
  "align-middle",
  "align-right",
  "amazon",
  "analyse",
  "anchor",
  "android",
  "angry",
  "angular",
  "aperture",
  "apple",
  "arch",
  "archive",
  "archive-in",
  "archive-out",
  "area",
  "arrow-back",
  "arrow-from-bottom",
  "arrow-from-left",
  "arrow-from-right",
  "arrow-from-top",
  "arrow-to-bottom",
  "arrow-to-left",
  "arrow-to-right",
  "arrow-to-top",
  "at",
  "atom",
  "audible",
  "award",
  "aws",
  "badge",
  "badge-check",
  "baguette",
  "baidu",
  "ball",
  "band-aid",
  "bar-chart",
  "bar-chart-alt",
  "bar-chart-alt-2",
  "bar-chart-square",
  "barcode",
  "barcode-reader",
  "baseball",
  "basket",
  "basketball",
  "bath",
  "battery",
  "bed",
  "been-here",
  "beer",
  "behance",
  "bell",
  "bell-minus",
  "bell-off",
  "bell-plus",
  "bible",
  "bing",
  "bitcoin",
  "blanket",
  "blender",
  "block",
  "blogger",
  "bluetooth",
  "body",
  "bold",
  "bolt-circle",
  "bomb",
  "bone",
  "bong",
  "book",
  "book-add",
  "book-alt",
  "book-bookmark",
  "book-content",
  "book-heart",
  "bookmark",
  "bookmark-alt",
  "bookmark-alt-minus",
  "bookmark-alt-plus",
  "bookmark-heart",
  "bookmark-minus",
  "bookmark-plus",
  "bookmarks",
  "book-open",
  "book-reader",
  "bootstrap",
  "border-all",
  "border-bottom",
  "border-inner",
  "border-left",
  "border-none",
  "border-outer",
  "border-radius",
  "border-right",
  "border-top",
  "bot",
  "bowl-hot",
  "bowling-ball",
  "bowl-rice",
  "box",
  "bracket",
  "braille",
  "brain",
  "briefcase",
  "briefcase-alt",
  "briefcase-alt-2",
  "brightness",
  "brightness-half",
  "broadcast",
  "brush",
  "brush-alt",
  "bug",
  "bug-alt",
  "building",
  "building-house",
  "buildings",
  "bulb",
  "bullseye",
  "buoy",
  "bus",
  "bus-school",
  "cabinet",
  "cable-car",
  "cake",
  "calculator",
  "calendar",
  "calendar-alt",
  "calendar-check",
  "calendar-edit",
  "calendar-event",
  "calendar-exclamation",
  "calendar-heart",
  "calendar-minus",
  "calendar-plus",
  "calendar-star",
  "calendar-week",
  "calendar-x",
  "camera",
  "camera-home",
  "camera-movie",
  "camera-off",
  "candles",
  "capsule",
  "captions",
  "car",
  "card",
  "caret-down",
  "caret-down-circle",
  "caret-down-square",
  "caret-left",
  "caret-left-circle",
  "caret-left-square",
  "caret-right",
  "caret-right-circle",
  "caret-right-square",
  "caret-up",
  "caret-up-circle",
  "caret-up-square",
  "carousel",
  "cart",
  "cart-add",
  "cart-alt",
  "cart-download",
  "cast",
  "category",
  "category-alt",
  "cctv",
  "certification",
  "chair",
  "chalkboard",
  "chart",
  "chat",
  "check",
  "checkbox",
  "checkbox-checked",
  "checkbox-minus",
  "checkbox-square",
  "check-circle",
  "check-double",
  "check-shield",
  "check-square",
  "cheese",
  "chevron-down",
  "chevron-down-circle",
  "chevron-down-square",
  "chevron-left",
  "chevron-left-circle",
  "chevron-left-square",
  "chevron-right",
  "chevron-right-circle",
  "chevron-right-square",
  "chevrons-down",
  "chevrons-left",
  "chevrons-right",
  "chevrons-up",
  "chevron-up",
  "chevron-up-circle",
  "chevron-up-square",
  "child",
  "chip",
  "chrome",
  "church",
  "circle",
  "circle-half",
  "circle-quarter",
  "circle-three-quarter",
  "clinic",
  "clipboard",
  "closet",
  "cloud",
  "cloud-download",
  "cloud-drizzle",
  "cloud-lightning",
  "cloud-light-rain",
  "cloud-rain",
  "cloud-snow",
  "cloud-upload",
  "code",
  "code-alt",
  "code-block",
  "code-curly",
  "codepen",
  "coffee",
  "coffee-togo",
  "cog",
  "coin",
  "coin-stack",
  "collapse",
  "collapse-alt",
  "collapse-horizontal",
  "collapse-vertical",
  "collection",
  "color",
  "color-fill",
  "columns",
  "command",
  "comment",
  "comment-add",
  "comment-check",
  "comment-detail",
  "comment-dots",
  "comment-edit",
  "comment-error",
  "comment-minus",
  "comment-x",
  "compass",
  "confused",
  "conversation",
  "cookie",
  "cool",
  "copy",
  "copy-alt",
  "copyright",
  "c-plus-plus",
  "creative-commons",
  "credit-card",
  "credit-card-alt",
  "credit-card-front",
  "cricket-ball",
  "crop",
  "cross",
  "crosshair",
  "crown",
  "css3",
  "cube",
  "cube-alt",
  "cuboid",
  "current-location",
  "customize",
  "cut",
  "cycling",
  "cylinder",
  "dailymotion",
  "data",
  "deezer",
  "desktop",
  "detail",
  "deviantart",
  "devices",
  "dev-to",
  "dialpad",
  "dialpad-alt",
  "diamond",
  "dice-1",
  "dice-2",
  "dice-3",
  "dice-4",
  "dice-5",
  "dice-6",
  "digg",
  "digitalocean",
  "directions",
  "disc",
  "discord",
  "discord-alt",
  "discourse",
  "dish",
  "dislike",
  "dizzy",
  "django",
  "dna",
  "dock-bottom",
  "docker",
  "dock-left",
  "dock-right",
  "dock-top",
  "dollar",
  "dollar-circle",
  "donate-blood",
  "donate-heart",
  "door-open",
  "dots-horizontal",
  "dots-horizontal-rounded",
  "dots-vertical",
  "dots-vertical-rounded",
  "doughnut-chart",
  "down-arrow",
  "down-arrow-alt",
  "down-arrow-circle",
  "download",
  "downvote",
  "dribbble",
  "drink",
  "dropbox",
  "droplet",
  "drupal",
  "dumbbell",
  "duplicate",
  "ebay",
  "edge",
  "edit",
  "edit-alt",
  "envelope",
  "envelope-open",
  "equalizer",
  "eraser",
  "error",
  "error-alt",
  "error-circle",
  "etsy",
  "euro",
  "exclude",
  "exit",
  "exit-fullscreen",
  "expand",
  "expand-alt",
  "expand-horizontal",
  "expand-vertical",
  "export",
  "extension",
  "face",
  "facebook",
  "facebook-circle",
  "facebook-square",
  "fast-forward",
  "fast-forward-circle",
  "female",
  "female-sign",
  "figma",
  "file",
  "file-blank",
  "file-find",
  "film",
  "filter",
  "filter-alt",
  "fingerprint",
  "firebase",
  "firefox",
  "first-aid",
  "first-page",
  "flag",
  "flask",
  "flickr",
  "flickr-square",
  "flutter",
  "folder",
  "folder-minus",
  "folder-open",
  "folder-plus",
  "font",
  "font-color",
  "font-family",
  "font-size",
  "food-menu",
  "food-tag",
  "football",
  "fork",
  "foursquare",
  "fridge",
  "fullscreen",
  "game",
  "gas-pump",
  "ghost",
  "gift",
  "git",
  "git-branch",
  "git-commit",
  "git-compare",
  "github",
  "gitlab",
  "git-merge",
  "git-pull-request",
  "git-repo-forked",
  "glasses",
  "glasses-alt",
  "globe",
  "globe-alt",
  "gmail",
  "go-lang",
  "google",
  "google-cloud",
  "google-plus",
  "google-plus-circle",
  "graphql",
  "grid",
  "grid-alt",
  "grid-horizontal",
  "grid-small",
  "grid-vertical",
  "group",
  "handicap",
  "happy",
  "happy-alt",
  "happy-beaming",
  "happy-heart-eyes",
  "hard-hat",
  "hash",
  "hdd",
  "heading",
  "headphone",
  "health",
  "heart",
  "heart-circle",
  "heart-square",
  "help-circle",
  "heroku",
  "hide",
  "highlight",
  "history",
  "hive",
  "home",
  "home-alt",
  "home-alt-2",
  "home-circle",
  "home-heart",
  "home-smile",
  "horizontal-center",
  "horizontal-left",
  "horizontal-right",
  "hotel",
  "hourglass",
  "html5",
  "id-card",
  "image",
  "image-add",
  "image-alt",
  "images",
  "imdb",
  "import",
  "infinite",
  "info-circle",
  "info-square",
  "injection",
  "instagram",
  "instagram-alt",
  "internet-explorer",
  "intersect",
  "invision",
  "italic",
  "java",
  "javascript",
  "joomla",
  "joystick",
  "joystick-alt",
  "joystick-button",
  "jquery",
  "jsfiddle",
  "key",
  "kickstarter",
  "knife",
  "kubernetes",
  "label",
  "landscape",
  "laptop",
  "last-page",
  "laugh",
  "layer",
  "layer-minus",
  "layer-plus",
  "layout",
  "leaf",
  "left-arrow",
  "left-arrow-alt",
  "left-arrow-circle",
  "left-down-arrow-circle",
  "left-indent",
  "left-top-arrow-circle",
  "lemon",
  "less",
  "library",
  "like",
  "line-chart",
  "line-chart-down",
  "link",
  "link-alt",
  "linkedin",
  "linkedin-square",
  "link-external",
  "lira",
  "list-check",
  "list-minus",
  "list-ol",
  "list-plus",
  "list-ul",
  "loader",
  "loader-alt",
  "loader-circle",
  "location-plus",
  "lock",
  "lock-alt",
  "lock-open",
  "lock-open-alt",
  "log-in",
  "log-in-circle",
  "log-out",
  "log-out-circle",
  "low-vision",
  "magento",
  "magnet",
  "mailchimp",
  "mail-send",
  "male",
  "male-female",
  "male-sign",
  "map",
  "map-alt",
  "map-pin",
  "markdown",
  "mask",
  "mastercard",
  "mastodon",
  "math",
  "medal",
  "medium",
  "medium-old",
  "medium-square",
  "meh",
  "meh-alt",
  "meh-blank",
  "memory-card",
  "menu",
  "menu-alt-left",
  "menu-alt-right",
  "merge",
  "message",
  "message-add",
  "message-alt",
  "message-alt-add",
  "message-alt-check",
  "message-alt-detail",
  "message-alt-dots",
  "message-alt-edit",
  "message-alt-error",
  "message-alt-minus",
  "message-alt-x",
  "message-check",
  "message-detail",
  "message-dots",
  "message-edit",
  "message-error",
  "message-minus",
  "message-rounded",
  "message-rounded-add",
  "message-rounded-check",
  "message-rounded-detail",
  "message-rounded-dots",
  "message-rounded-edit",
  "message-rounded-error",
  "message-rounded-minus",
  "message-rounded-x",
  "message-square",
  "message-square-add",
  "message-square-check",
  "message-square-detail",
  "message-square-dots",
  "message-square-edit",
  "message-square-error",
  "message-square-minus",
  "message-square-x",
  "message-x",
  "messenger",
  "meta",
  "meteor",
  "microchip",
  "microphone",
  "microphone-off",
  "microsoft",
  "microsoft-teams",
  "minus",
  "minus-back",
  "minus-circle",
  "minus-front",
  "mobile",
  "mobile-alt",
  "mobile-landscape",
  "mobile-vibration",
  "money",
  "money-withdraw",
  "mongodb",
  "moon",
  "mouse",
  "mouse-alt",
  "move",
  "move-horizontal",
  "move-vertical",
  "movie",
  "movie-play",
  "music",
  "navigation",
  "netlify",
  "network-chart",
  "news",
  "nodejs",
  "no-entry",
  "no-signal",
  "note",
  "notepad",
  "notification",
  "notification-off",
  "objects-horizontal-center",
  "objects-horizontal-left",
  "objects-horizontal-right",
  "objects-vertical-bottom",
  "objects-vertical-center",
  "objects-vertical-top",
  "ok-ru",
  "opera",
  "outline",
  "package",
  "paint",
  "paint-roll",
  "palette",
  "paperclip",
  "paper-plane",
  "paragraph",
  "party",
  "paste",
  "patreon",
  "pause",
  "pause-circle",
  "paypal",
  "pen",
  "pencil",
  "periscope",
  "phone",
  "phone-call",
  "phone-incoming",
  "phone-off",
  "phone-outgoing",
  "photo-album",
  "php",
  "pie-chart",
  "pie-chart-alt",
  "pie-chart-alt-2",
  "pin",
  "pinterest",
  "pinterest-alt",
  "planet",
  "play",
  "play-circle",
  "play-store",
  "plug",
  "plus",
  "plus-circle",
  "plus-medical",
  "pocket",
  "podcast",
  "pointer",
  "poll",
  "polygon",
  "popsicle",
  "postgresql",
  "pound",
  "power-off",
  "printer",
  "product-hunt",
  "pulse",
  "purchase-tag",
  "purchase-tag-alt",
  "pyramid",
  "python",
  "qr",
  "qr-scan",
  "question-mark",
  "quora",
  "radar",
  "radio",
  "radio-circle",
  "radio-circle-marked",
  "react",
  "receipt",
  "rectangle",
  "recycle",
  "redbubble",
  "reddit",
  "redo",
  "redux",
  "reflect-horizontal",
  "reflect-vertical",
  "refresh",
  "registered",
  "rename",
  "repeat",
  "reply",
  "reply-all",
  "repost",
  "reset",
  "restaurant",
  "revision",
  "rewind",
  "rewind-circle",
  "rfid",
  "right-arrow",
  "right-arrow-alt",
  "right-arrow-circle",
  "right-down-arrow-circle",
  "right-indent",
  "right-top-arrow-circle",
  "rocket",
  "rotate-left",
  "rotate-right",
  "rss",
  "ruble",
  "ruler",
  "run",
  "rupee",
  "sad",
  "sass",
  "save",
  "scan",
  "scatter-chart",
  "screenshot",
  "search",
  "search-alt",
  "search-alt-2",
  "selection",
  "select-multiple",
  "send",
  "server",
  "shape-circle",
  "shape-polygon",
  "shape-square",
  "shape-triangle",
  "share",
  "share-alt",
  "shekel",
  "shield",
  "shield-alt",
  "shield-alt-2",
  "shield-minus",
  "shield-plus",
  "shield-quarter",
  "shield-x",
  "shocked",
  "shopify",
  "shopping-bag",
  "show",
  "show-alt",
  "shower",
  "shuffle",
  "sidebar",
  "signal-1",
  "signal-2",
  "signal-3",
  "signal-4",
  "signal-5",
  "sitemap",
  "sketch",
  "skip-next",
  "skip-next-circle",
  "skip-previous",
  "skip-previous-circle",
  "skype",
  "slack",
  "slack-old",
  "sleepy",
  "slider",
  "slider-alt",
  "slideshow",
  "smile",
  "snapchat",
  "sort",
  "sort-alt-2",
  "sort-a-z",
  "sort-down",
  "sort-up",
  "sort-z-a",
  "soundcloud",
  "spa",
  "space-bar",
  "speaker",
  "spotify",
  "spray-can",
  "spreadsheet",
  "spring-boot",
  "square",
  "square-rounded",
  "squarespace",
  "stack-overflow",
  "star",
  "station",
  "stats",
  "steam",
  "sticker",
  "stop",
  "stop-circle",
  "stopwatch",
  "store",
  "store-alt",
  "street-view",
  "strikethrough",
  "stripe",
  "subdirectory-left",
  "subdirectory-right",
  "sun",
  "support",
  "sushi",
  "swim",
  "sync",
  "tab",
  "table",
  "tachometer",
  "tag",
  "tag-alt",
  "tailwind-css",
  "target-lock",
  "task",
  "task-x",
  "taxi",
  "telegram",
  "tennis-ball",
  "terminal",
  "test-tube",
  "text",
  "tiktok",
  "time",
  "time-five",
  "timer",
  "tired",
  "toggle-left",
  "toggle-right",
  "tone",
  "traffic-cone",
  "train",
  "transfer",
  "transfer-alt",
  "trash",
  "trash-alt",
  "trello",
  "trending-down",
  "trending-up",
  "trim",
  "trip",
  "trip-advisor",
  "trophy",
  "tumblr",
  "tux",
  "tv",
  "twitch",
  "twitter",
  "typescript",
  "underline",
  "undo",
  "unite",
  "unity",
  "universal-access",
  "unlink",
  "unsplash",
  "up-arrow",
  "up-arrow-alt",
  "up-arrow-circle",
  "upload",
  "upside-down",
  "upvote",
  "upwork",
  "usb",
  "user",
  "user-check",
  "user-circle",
  "user-minus",
  "user-pin",
  "user-plus",
  "user-voice",
  "user-x",
  "vector",
  "venmo",
  "vertical-bottom",
  "vertical-center",
  "vertical-top",
  "vial",
  "video",
  "video-off",
  "video-plus",
  "video-recording",
  "vimeo",
  "visa",
  "visual-studio",
  "vk",
  "voicemail",
  "volume",
  "volume-full",
  "volume-low",
  "volume-mute",
  "vuejs",
  "walk",
  "wallet",
  "wallet-alt",
  "water",
  "webcam",
  "whatsapp",
  "whatsapp-square",
  "wifi",
  "wifi-0",
  "wifi-1",
  "wifi-2",
  "wifi-off",
  "wikipedia",
  "wind",
  "window",
  "window-alt",
  "window-close",
  "window-open",
  "windows",
  "wine",
  "wink-smile",
  "wink-tongue",
  "wix",
  "won",
  "wordpress",
  "world",
  "wrench",
  "x",
  "x-circle",
  "xing",
  "yahoo",
  "yelp",
  "yen",
  "youtube",
  "zoom",
  "zoom-in",
  "zoom-out"
];

// Ícones SOLID (wfs) - 665 ícones
var SOLID_ICONS = [
  "add-to-queue",
  "adjust",
  "adjust-alt",
  "alarm",
  "alarm-add",
  "alarm-exclamation",
  "alarm-off",
  "alarm-snooze",
  "album",
  "ambulance",
  "analyse",
  "angry",
  "arch",
  "archive",
  "archive-in",
  "archive-out",
  "area",
  "arrow-from-bottom",
  "arrow-from-left",
  "arrow-from-right",
  "arrow-from-top",
  "arrow-to-bottom",
  "arrow-to-left",
  "arrow-to-right",
  "arrow-to-top",
  "award",
  "baby-carriage",
  "backpack",
  "badge",
  "badge-check",
  "badge-dollar",
  "baguette",
  "ball",
  "balloon",
  "band-aid",
  "bank",
  "bar-chart-alt-2",
  "bar-chart-square",
  "barcode",
  "baseball",
  "basket",
  "basketball",
  "bath",
  "battery",
  "battery-charging",
  "battery-full",
  "battery-low",
  "bed",
  "been-here",
  "beer",
  "bell",
  "bell-minus",
  "bell-off",
  "bell-plus",
  "bell-ring",
  "bible",
  "binoculars",
  "blanket",
  "bolt",
  "bolt-circle",
  "bomb",
  "bone",
  "bong",
  "book",
  "book-add",
  "book-alt",
  "book-bookmark",
  "book-content",
  "book-heart",
  "bookmark",
  "bookmark-alt",
  "bookmark-alt-minus",
  "bookmark-alt-plus",
  "bookmark-heart",
  "bookmark-minus",
  "bookmark-plus",
  "bookmarks",
  "bookmark-star",
  "book-open",
  "book-reader",
  "bot",
  "bowl-hot",
  "bowling-ball",
  "bowl-rice",
  "box",
  "brain",
  "briefcase",
  "briefcase-alt",
  "briefcase-alt-2",
  "brightness",
  "brightness-half",
  "brush",
  "brush-alt",
  "bug",
  "bug-alt",
  "building",
  "building-house",
  "buildings",
  "bulb",
  "bullseye",
  "buoy",
  "bus",
  "business",
  "bus-school",
  "cabinet",
  "cable-car",
  "cake",
  "calculator",
  "calendar",
  "calendar-alt",
  "calendar-check",
  "calendar-edit",
  "calendar-event",
  "calendar-exclamation",
  "calendar-heart",
  "calendar-minus",
  "calendar-plus",
  "calendar-star",
  "calendar-week",
  "calendar-x",
  "camera",
  "camera-home",
  "camera-movie",
  "camera-off",
  "camera-plus",
  "capsule",
  "captions",
  "car",
  "car-battery",
  "car-crash",
  "card",
  "caret-down-circle",
  "caret-down-square",
  "caret-left-circle",
  "caret-left-square",
  "caret-right-circle",
  "caret-right-square",
  "caret-up-circle",
  "caret-up-square",
  "car-garage",
  "car-mechanic",
  "carousel",
  "cart",
  "cart-add",
  "cart-alt",
  "cart-download",
  "car-wash",
  "castle",
  "cat",
  "category",
  "category-alt",
  "cctv",
  "certification",
  "chalkboard",
  "chart",
  "chat",
  "checkbox",
  "checkbox-checked",
  "checkbox-minus",
  "check-circle",
  "check-shield",
  "check-square",
  "cheese",
  "chess",
  "chevron-down",
  "chevron-down-circle",
  "chevron-down-square",
  "chevron-left",
  "chevron-left-circle",
  "chevron-left-square",
  "chevron-right",
  "chevron-right-circle",
  "chevron-right-square",
  "chevrons-down",
  "chevrons-left",
  "chevrons-right",
  "chevrons-up",
  "chevron-up",
  "chevron-up-circle",
  "chevron-up-square",
  "chip",
  "church",
  "circle",
  "circle-half",
  "circle-quarter",
  "circle-three-quarter",
  "city",
  "clinic",
  "cloud",
  "cloud-download",
  "cloud-lightning",
  "cloud-rain",
  "cloud-upload",
  "coffee",
  "coffee-alt",
  "coffee-bean",
  "coffee-togo",
  "cog",
  "coin",
  "coin-stack",
  "collection",
  "color",
  "color-fill",
  "comment",
  "comment-add",
  "comment-check",
  "comment-detail",
  "comment-dots",
  "comment-edit",
  "comment-error",
  "comment-minus",
  "comment-x",
  "compass",
  "component",
  "confused",
  "contact",
  "conversation",
  "cookie",
  "cool",
  "copy",
  "copy-alt",
  "copyright",
  "coupon",
  "credit-card",
  "credit-card-alt",
  "credit-card-front",
  "cricket-ball",
  "crop",
  "crown",
  "cube",
  "cube-alt",
  "cuboid",
  "customize",
  "cylinder",
  "dashboard",
  "data",
  "detail",
  "devices",
  "diamond",
  "dice-1",
  "dice-2",
  "dice-3",
  "dice-4",
  "dice-5",
  "dice-6",
  "direction-left",
  "direction-right",
  "directions",
  "disc",
  "discount",
  "dish",
  "dislike",
  "dizzy",
  "dock-bottom",
  "dock-left",
  "dock-right",
  "dock-top",
  "dog",
  "dollar-circle",
  "donate-blood",
  "donate-heart",
  "door-open",
  "doughnut-chart",
  "down-arrow",
  "down-arrow-alt",
  "down-arrow-circle",
  "down-arrow-square",
  "download",
  "downvote",
  "drink",
  "droplet",
  "droplet-half",
  "dryer",
  "duplicate",
  "edit",
  "edit-alt",
  "edit-location",
  "eject",
  "envelope",
  "envelope-open",
  "eraser",
  "error",
  "error-alt",
  "error-circle",
  "ev-station",
  "exit",
  "extension",
  "eyedropper",
  "face",
  "face-mask",
  "factory",
  "fast-forward-circle",
  "file",
  "file-archive",
  "file-blank",
  "file-css",
  "file-doc",
  "file-export",
  "file-find",
  "file-gif",
  "file-html",
  "file-image",
  "file-import",
  "file-jpg",
  "file-js",
  "file-json",
  "file-md",
  "file-pdf",
  "file-plus",
  "file-png",
  "file-txt",
  "film",
  "filter-alt",
  "first-aid",
  "flag",
  "flag-alt",
  "flag-checkered",
  "flame",
  "flask",
  "florist",
  "folder",
  "folder-minus",
  "folder-open",
  "folder-plus",
  "food-menu",
  "fridge",
  "game",
  "gas-pump",
  "ghost",
  "gift",
  "graduation",
  "grid",
  "grid-alt",
  "group",
  "guitar-amp",
  "hand",
  "hand-down",
  "hand-left",
  "hand-right",
  "hand-up",
  "happy",
  "happy-alt",
  "happy-beaming",
  "happy-heart-eyes",
  "hard-hat",
  "hdd",
  "heart",
  "heart-circle",
  "heart-square",
  "help-circle",
  "hide",
  "home",
  "home-alt-2",
  "home-circle",
  "home-heart",
  "home-smile",
  "hot",
  "hotel",
  "hourglass",
  "hourglass-bottom",
  "hourglass-top",
  "id-card",
  "image",
  "image-add",
  "image-alt",
  "inbox",
  "info-circle",
  "info-square",
  "injection",
  "institution",
  "invader",
  "joystick",
  "joystick-alt",
  "joystick-button",
  "key",
  "keyboard",
  "label",
  "landmark",
  "landscape",
  "laugh",
  "layer",
  "layer-minus",
  "layer-plus",
  "layout",
  "leaf",
  "left-arrow",
  "left-arrow-alt",
  "left-arrow-circle",
  "left-arrow-square",
  "left-down-arrow-circle",
  "left-top-arrow-circle",
  "lemon",
  "like",
  "location-plus",
  "lock",
  "lock-alt",
  "lock-open",
  "lock-open-alt",
  "log-in",
  "log-in-circle",
  "log-out",
  "log-out-circle",
  "low-vision",
  "magic-wand",
  "magnet",
  "map",
  "map-alt",
  "map-pin",
  "mask",
  "medal",
  "megaphone",
  "meh",
  "meh-alt",
  "meh-blank",
  "memory-card",
  "message",
  "message-add",
  "message-alt",
  "message-alt-add",
  "message-alt-check",
  "message-alt-detail",
  "message-alt-dots",
  "message-alt-edit",
  "message-alt-error",
  "message-alt-minus",
  "message-alt-x",
  "message-check",
  "message-detail",
  "message-dots",
  "message-edit",
  "message-error",
  "message-minus",
  "message-rounded",
  "message-rounded-add",
  "message-rounded-check",
  "message-rounded-detail",
  "message-rounded-dots",
  "message-rounded-edit",
  "message-rounded-error",
  "message-rounded-minus",
  "message-rounded-x",
  "message-square",
  "message-square-add",
  "message-square-check",
  "message-square-detail",
  "message-square-dots",
  "message-square-edit",
  "message-square-error",
  "message-square-minus",
  "message-square-x",
  "message-x",
  "meteor",
  "microchip",
  "microphone",
  "microphone-alt",
  "microphone-off",
  "minus-circle",
  "minus-square",
  "mobile",
  "mobile-vibration",
  "moon",
  "mouse",
  "mouse-alt",
  "movie",
  "movie-play",
  "music",
  "navigation",
  "network-chart",
  "news",
  "no-entry",
  "note",
  "notepad",
  "notification",
  "notification-off",
  "objects-horizontal-center",
  "objects-horizontal-left",
  "objects-horizontal-right",
  "objects-vertical-bottom",
  "objects-vertical-center",
  "objects-vertical-top",
  "offer",
  "package",
  "paint",
  "paint-roll",
  "palette",
  "paper-plane",
  "parking",
  "party",
  "paste",
  "pear",
  "pen",
  "pencil",
  "phone",
  "phone-call",
  "phone-incoming",
  "phone-off",
  "phone-outgoing",
  "photo-album",
  "piano",
  "pie-chart",
  "pie-chart-alt",
  "pie-chart-alt-2",
  "pin",
  "pizza",
  "plane",
  "plane-alt",
  "plane-land",
  "planet",
  "plane-take-off",
  "playlist",
  "plug",
  "plus-circle",
  "plus-square",
  "pointer",
  "polygon",
  "popsicle",
  "printer",
  "purchase-tag",
  "purchase-tag-alt",
  "pyramid",
  "quote-alt-left",
  "quote-alt-right",
  "quote-left",
  "quote-right",
  "quote-single-left",
  "quote-single-right",
  "radiation",
  "radio",
  "receipt",
  "rectangle",
  "registered",
  "rename",
  "report",
  "rewind-circle",
  "right-arrow",
  "right-arrow-alt",
  "right-arrow-circle",
  "right-arrow-square",
  "right-down-arrow-circle",
  "right-top-arrow-circle",
  "rocket",
  "ruler",
  "sad",
  "save",
  "school",
  "search",
  "search-alt-2",
  "select-multiple",
  "send",
  "server",
  "shapes",
  "share",
  "share-alt",
  "shield",
  "shield-alt-2",
  "shield-minus",
  "shield-plus",
  "shield-x",
  "ship",
  "shocked",
  "shopping-bag",
  "shopping-bag-alt",
  "shopping-bags",
  "show",
  "shower",
  "skip-next-circle",
  "skip-previous-circle",
  "skull",
  "sleepy",
  "slideshow",
  "smile",
  "sort-alt",
  "spa",
  "speaker",
  "spray-can",
  "spreadsheet",
  "square",
  "square-rounded",
  "star",
  "star-half",
  "sticker",
  "stopwatch",
  "store",
  "store-alt",
  "sun",
  "sushi",
  "tachometer",
  "tag",
  "tag-alt",
  "tag-x",
  "taxi",
  "tennis-ball",
  "terminal",
  "thermometer",
  "time",
  "time-five",
  "timer",
  "tired",
  "toggle-left",
  "toggle-right",
  "tone",
  "torch",
  "to-top",
  "traffic",
  "traffic-barrier",
  "traffic-cone",
  "train",
  "trash",
  "trash-alt",
  "tree",
  "tree-alt",
  "trophy",
  "truck",
  "t-shirt",
  "tv",
  "universal-access",
  "up-arrow",
  "up-arrow-alt",
  "up-arrow-circle",
  "up-arrow-square",
  "upside-down",
  "upvote",
  "user",
  "user-account",
  "user-badge",
  "user-check",
  "user-circle",
  "user-detail",
  "user-minus",
  "user-pin",
  "user-plus",
  "user-rectangle",
  "user-voice",
  "user-x",
  "vector",
  "vial",
  "video",
  "video-off",
  "video-plus",
  "video-recording",
  "videos",
  "virus",
  "virus-block",
  "volume",
  "volume-full",
  "volume-low",
  "volume-mute",
  "wallet",
  "wallet-alt",
  "washer",
  "watch",
  "watch-alt",
  "webcam",
  "widget",
  "window-alt",
  "wine",
  "wink-smile",
  "wink-tongue",
  "wrench",
  "x-circle",
  "x-square",
  "yin-yang",
  "zap",
  "zoom-in",
  "zoom-out"
];

// Ícones LOGOS (wfl) - 155 ícones
var LOGOS_ICONS = [
  "500px",
  "99designs",
  "adobe",
  "airbnb",
  "algolia",
  "amazon",
  "android",
  "angular",
  "apple",
  "audible",
  "aws",
  "baidu",
  "behance",
  "bing",
  "bitcoin",
  "blender",
  "blogger",
  "bootstrap",
  "chrome",
  "codepen",
  "c-plus-plus",
  "creative-commons",
  "css3",
  "dailymotion",
  "deezer",
  "deviantart",
  "dev-to",
  "digg",
  "digitalocean",
  "discord",
  "discord-alt",
  "discourse",
  "django",
  "docker",
  "dribbble",
  "dropbox",
  "drupal",
  "ebay",
  "edge",
  "etsy",
  "facebook",
  "facebook-circle",
  "facebook-square",
  "figma",
  "firebase",
  "firefox",
  "flask",
  "flickr",
  "flickr-square",
  "flutter",
  "foursquare",
  "git",
  "github",
  "gitlab",
  "gmail",
  "go-lang",
  "google",
  "google-cloud",
  "google-plus",
  "google-plus-circle",
  "graphql",
  "heroku",
  "html5",
  "imdb",
  "instagram",
  "instagram-alt",
  "internet-explorer",
  "invision",
  "java",
  "javascript",
  "joomla",
  "jquery",
  "jsfiddle",
  "kickstarter",
  "kubernetes",
  "less",
  "linkedin",
  "linkedin-square",
  "magento",
  "mailchimp",
  "markdown",
  "mastercard",
  "mastodon",
  "medium",
  "medium-old",
  "medium-square",
  "messenger",
  "meta",
  "microsoft",
  "microsoft-teams",
  "mongodb",
  "netlify",
  "nodejs",
  "ok-ru",
  "opera",
  "patreon",
  "paypal",
  "periscope",
  "php",
  "pinterest",
  "pinterest-alt",
  "play-store",
  "pocket",
  "postgresql",
  "product-hunt",
  "python",
  "quora",
  "react",
  "redbubble",
  "reddit",
  "redux",
  "sass",
  "shopify",
  "sketch",
  "skype",
  "slack",
  "slack-old",
  "snapchat",
  "soundcloud",
  "spotify",
  "spring-boot",
  "squarespace",
  "stack-overflow",
  "steam",
  "stripe",
  "tailwind-css",
  "telegram",
  "tiktok",
  "trello",
  "trip-advisor",
  "tumblr",
  "tux",
  "twitch",
  "twitter",
  "typescript",
  "unity",
  "unsplash",
  "upwork",
  "venmo",
  "vimeo",
  "visa",
  "visual-studio",
  "vk",
  "vuejs",
  "whatsapp",
  "whatsapp-square",
  "wikipedia",
  "windows",
  "wix",
  "wordpress",
  "xing",
  "yahoo",
  "yelp",
  "youtube",
  "zoom"
];

    var currentFilter = 'all';
    var currentSearch = '';

    function getFilteredIcons() {
      var list = [];

      if (currentFilter === 'all') {
        list = REGULAR_ICONS.map(function(n) { return { name: n, prefix: 'wf' }; })
          .concat(SOLID_ICONS.map(function(n) { return { name: n, prefix: 'wfs' }; }))
          .concat(LOGOS_ICONS.map(function(n) { return { name: n, prefix: 'wfl' }; }));
      } else if (currentFilter === 'wf') {
        list = REGULAR_ICONS.map(function(n) { return { name: n, prefix: 'wf' }; });
      } else if (currentFilter === 'wfs') {
        list = SOLID_ICONS.map(function(n) { return { name: n, prefix: 'wfs' }; });
      } else if (currentFilter === 'wfl') {
        list = LOGOS_ICONS.map(function(n) { return { name: n, prefix: 'wfl' }; });
      }

      if (currentSearch) {
        list = list.filter(function(icon) {
          return icon.name.indexOf(currentSearch) !== -1;
        });
      }

      return list;
    }

    function render() {
      var list = getFilteredIcons();
      var ul = document.getElementById('wficons-list');
      var countEl = document.getElementById('icon-count');

      if (!ul) return;

      ul.innerHTML = '';

      list.forEach(function(icon) {
        var li = document.createElement('li');
        var iconClass = icon.prefix + ' ' + icon.prefix + '-' + icon.name;
        var copyText = icon.prefix + '-' + icon.name;

        li.innerHTML =
          '<a href="#" data-copy="' + copyText + '">' +
          '<div><i class="' + iconClass + '"></i></div>' +
          '<p>' + copyText + '</p>' +
          '</a>';

        ul.appendChild(li);

        var a = li.querySelector('a');
        if (a) {
          a.addEventListener('click', function(e) {
            e.preventDefault();
            var copyName = this.getAttribute('data-copy') || '';

            try {
              navigator.clipboard.writeText(copyName).then(function() {
                a.classList.add('copied');
                var p = a.querySelector('p');

                if (p) {
                  var orig = p.textContent;
                  p.textContent = copyName + ' copiado!';

                  setTimeout(function() {
                    p.textContent = orig;
                    a.classList.remove('copied');
                  }, 1200);
                } else {
                  setTimeout(function() {
                    a.classList.remove('copied');
                  }, 1200);
                }
              });
            } catch (_) {}
          });
        }
      });

      if (countEl) {
        var totalText = list.length + ' de ';

        if (currentFilter === 'all') {
          totalText += (REGULAR_ICONS.length + SOLID_ICONS.length + LOGOS_ICONS.length) + ' ícones';
        } else if (currentFilter === 'wf') {
          totalText += REGULAR_ICONS.length + ' ícones';
        } else if (currentFilter === 'wfs') {
          totalText += SOLID_ICONS.length + ' ícones';
        } else if (currentFilter === 'wfl') {
          totalText += LOGOS_ICONS.length + ' ícones';
        }

        countEl.textContent = totalText;
      }
    }

    function init() {
      // Filtros
      var filterButtons = document.querySelectorAll('.filter-btn');
      filterButtons.forEach(function(btn) {
        btn.addEventListener('click', function() {
          filterButtons.forEach(function(b) { b.classList.remove('active'); });
          this.classList.add('active');
          currentFilter = this.getAttribute('data-filter');
          render();
        });
      });

      // Busca
      var input = document.getElementById('icon-search');
      if (input) {
        input.addEventListener('input', function() {
          currentSearch = (this.value || '').toLowerCase().trim();
          render();
        });
      }

      // Renderizar inicial
      render();
    }

    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', init);
    } else {
      init();
    }

    try {
      document.addEventListener('wfajax:loaded', init);
      document.addEventListener('wfajax:complete', init);
    } catch (_) {}
  })();
</script>
